---
title: "R Notebook"
output: html_notebook
---


```{r}
library(scMAGeCK)
library(biomaRt)
library(ComplexHeatmap)
library(circlize)
library(tidyverse)
library(data.table)
library(Seurat)
library(optparse)
library(ggplot2)
library(ggrepel)
library(viridis)
#library(qs)
library(gridExtra)
library(Rcpp)
library(scDblFinder)
library(ggrastr)
library(Matrix)
library(tibble)
library(dplyr)
library(RColorBrewer)
library(ggpubr)
library(clusterProfiler)
library(org.Hs.eg.db)

```

```{r}
select <- dplyr::select
rename <- dplyr::rename
slice <- dplyr::slice
map <- purrr::map
mutate <- dplyr::mutate
filter<-dplyr::filter

#dir <- "/g/steinmetz/project/otar/software/BD2.2/full_data_per_panel/"
#indir <- paste0(dir, "output")
outdir <- paste0("/g/steinmetz/moonen/Rstudio/screen_analyses_DM/results")

## load result files
results_path <- "/g/steinmetz/moonen/Rstudio/screen_analyses_DM/results"

# Get the list of all folders named Panel1 to Panel16
panel_folders <- list.files(results_path, pattern = "Panel[1-9]|Panel1[0-6]", full.names = TRUE, include.dirs = TRUE)

# Function to read a discovery_results.tsv file from a given folder
read_discovery_results <- function(folder) {
  file_path <- file.path(folder, "discovery_results.tsv")
  if (file.exists(file_path)) {
    return(read.delim(file_path, header = TRUE, sep = "\t"))
  } else {
    return(NULL)
  }
}

# Read all discovery_results.tsv files into a list
discovery_results_list <- lapply(panel_folders, read_discovery_results)

# Optionally, you can remove NULL entries if any folder does not contain the file
discovery_results_list <- Filter(Negate(is.null), discovery_results_list)

results_df <- bind_rows(discovery_results_list)


#load gene data
genes <- read_tsv("/g/steinmetz/moonen/Rstudio/screen_analyses/resources/gene_tss.tsv", show_col_types = FALSE)
# add gene TSS coordinates to results and derive enhancer coordinates from id
results_df <- results_df %>% 
  left_join(genes, by = "response_id") %>% 
  rename(gene_chr = chr, gene_tss = position) %>% 
  separate(grna_target, into = c("pert_chr", "pert_start", "pert_end"), sep = ":|-",
           remove = FALSE, fill = "right", convert = TRUE) %>% 
  mutate(pert_chr = if_else(is.na(pert_start), true = NA_character_, false = pert_chr))


## load gRNA library details
# Define the path to the folder containing the CSV files
grna_lib_list <- list()
grna_lib_list[[1]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_1_2023-12-22.csv')
grna_lib_list[[2]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_2_2023-12-22.csv')
grna_lib_list[[3]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_3_2023-12-22.csv')
grna_lib_list[[4]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_4_2023-12-22.csv')
grna_lib_list[[5]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_5_2023-12-22.csv')
grna_lib_list[[6]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_6_2023-12-22.csv')
grna_lib_list[[7]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_7_2023-12-22.csv')
grna_lib_list[[8]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_8_2023-12-22.csv')
grna_lib_list[[9]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_9_2023-12-22.csv')
grna_lib_list[[10]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_10_2023-12-22.csv')
grna_lib_list[[11]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_11_2023-12-22.csv')
grna_lib_list[[12]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_12_2023-12-22.csv')
grna_lib_list[[13]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_13_2023-12-22.csv')
grna_lib_list[[14]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_14_2023-12-22.csv')
grna_lib_list[[15]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_15_2023-12-22.csv')
grna_lib_list[[16]] <- read_csv('/g/steinmetz/project/otar/select_enhancer_peaks/guide_design/output/gRNA_info_vivlion_panel_16_2023-12-22.csv')

grna_lib <- bind_rows(grna_lib_list)



targets <- grna_lib %>% 
  select(peak = peak, target_gene = target_gene) %>%
  unique()


##convert target_gene to gene symbols
ensembl_ids <- unique(unlist(strsplit(targets$target_gene, ";")))

# Set up the biomaRt connection to the Ensembl database
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# Query the database to get the gene names
gene_info <- getBM(attributes = c('ensembl_gene_id', 'hgnc_symbol'), 
                   filters = 'ensembl_gene_id', 
                   values = ensembl_ids, 
                   mart = ensembl)

# Create a named vector for easier replacement
gene_map <- setNames(gene_info$hgnc_symbol, gene_info$ensembl_gene_id)

# Replace Ensembl IDs with gene names in the target_gene column
# scmageck_res_tbl_comb <- scmageck_res_tbl_comb %>%
#   rowwise() %>%
#   mutate(target_gene = paste(gene_map[unlist(strsplit(target_gene, ";"))], collapse = ";")) %>%
#   ungroup()

targets <- targets %>%
  rowwise() %>%
  mutate(target_genes = paste(gene_map[unlist(strsplit(target_gene, ";"))], collapse = ";")) %>%
  ungroup()

targets <- targets %>%
  mutate(target_genes = ifelse(target_genes=="NA", target_gene, target_genes)) %>% 
  select(peak, target_genes)

results_df <- results_df %>%
  left_join(targets, by = c("grna_target" = "peak")) %>%
  mutate(target_genes =ifelse(is.na(target_genes), grna_target, target_genes)) 


results_df <- results_df %>%
  mutate(is_target = sapply(1:n(), function(i) {
    target_list <- unlist(strsplit(target_genes[i], ";"))
    response_id[i] %in% target_list
  }))

results_df <- results_df %>% 
  mutate(distance = if_else(
    pert_chr == gene_chr,
    true = (pert_start + pert_end) / 2 - gene_tss,
    false = NA_integer_))


```

```{r}

##plot distance against effect size


symlog_trans <- function() {
   trans <- function(x) sign(x) * log1p(abs(x))
   inv <- function(x) sign(x) * (exp(abs(x)) - 1)
   scales::trans_new(name = 'symlog', transform = trans, inverse = inv)
 }
 
 symlog_breaks <- function(limits) {
   breaks <- unique(c(-rev(10^seq(0, log10(abs(limits[1])), length.out = 5)),
                      0,
                      10^seq(0, log10(abs(limits[2])), length.out = 5)))
   breaks
 }
 custom_breaks <- c(-500000, -100000, -50000, -10000, -5000, -1000, -500, -100, -50, -10, 0, 10, 50, 100, 500, 1000, 5000, 10000, 50000, 100000, 500000)
 
expr_change_dist <- ggplot(results_df %>% filter(significant==TRUE) %>% filter(pert_chr == gene_chr), aes(x = (distance / 1000), y = log_2_fold_change, color = as.factor(gene_chr), shape = is_target)) +
   geom_point(alpha = 0.5, fill = NA, stroke = 1) +
   scale_color_discrete(name = "Chromosome") +  # Automatically generate colors for chromosomes
   scale_size_continuous(range = c(0.075, 3), guide = guide_legend(title = "1/(p-value)")) +
   scale_shape_manual(name = "Expected target", values = c("TRUE" = 16, "FALSE" = 21), labels = c("Yes" = "TRUE", "No" = "FALSE")) +
  scale_x_continuous(trans = symlog_trans(), breaks = custom_breaks, name = "Logarithmic Distance to TSS (kb, symlog scale)") +
   labs(
     title = "Distance to TSS vs. Expression Change",
     y = "Expression change (log2FC)",
     x = "Distance to TSS (kb)" ) +
   #xlim(-1000, 1000)+
   theme_minimal() +
   theme(
     legend.position = "right",
     legend.title.align = 0.5,
     plot.title = element_text(hjust = 0.5),
     plot.subtitle = element_text(hjust = 0.5),
     axis.text.x = element_text(angle = 45, hjust = 1)  # Rotate x-axis labels to 45 degrees
   ) +
 geom_vline(xintercept = c(-1.5, 1.5), linetype = "dotted", color = "red", size = 1) +
 geom_vline(xintercept = c(-10, 10), linetype = "dotted", color = "grey", size = 1)


 pdf(paste0(outdir, "/distance_gene_expr_change_all_panels.pdf"), height = 6, width = 12)
 expr_change_dist
 dev.off()

```


```{r}
## Vulcanoplot

####vulcano plot

results_df<-results_df%>% 
  mutate(pval_scaled = -log10(p_value + 1e-15))
 
# Generate the volcano plot
vulcano <- ggplot(results_df %>% filter(pert_chr == gene_chr), aes(x = log_2_fold_change, y = pval_scaled)) +
  geom_point(aes(
    fill = significant, 
    color = ifelse(is_target, "TRUE", "FALSE")
  ), shape = 21, size = 2.5, stroke = 0.5) +
  scale_fill_manual(
    values = c('FALSE' = '#dddddd', 'TRUE' = '#4285f4'), 
    name = "Significant"
  ) +
  scale_color_manual(
    values = c('TRUE' = 'red', 'FALSE' = NA),
    name = "Predicted Target",
    labels = c('FALSE', 'TRUE')
  ) +
  labs(
    x = "Log fold change",
    y = "-log(p-value)",
    title = "Volcano Plot"
  ) +
  theme_minimal() +
  theme(legend.position = "right")

pdf(paste0(outdir, "/Vulcano.pdf"), height = 6, width = 12)
 vulcano
 dev.off()


```

```{r}
## comparing scmageck and SCEPTRE. taking along only the overlapping results

#load scmageck results
scmageck<- readRDS("/g/steinmetz/project/otar/software/BD2.2/full_data_per_panel/results/scmageck_all_panels.rds")

scmageck <- scmageck %>% mutate(significant = padj <= 0.001)
scmageck <- scmageck%>% mutate(pval_scaled = -log10(padj + 1e-15))

scmageck_significant <- scmageck %>% filter(significant == TRUE, grepl("^chr", guide_target))
results_df_significant <- results_df %>% filter(significant == TRUE, grepl("^chr", grna_target))


scmageck_set <- scmageck_significant %>% 
  select(guide_target, gene) %>% 
  unite("key", guide_target, gene, sep = "_")

results_df_set <- results_df_significant %>% 
  select(grna_target, response_id) %>% 
  unite("key", `grna_target`, response_id, sep = "_")

scmageck_significant <- scmageck_significant %>%
  mutate(key = paste(guide_target, gene, sep = "_"))

results_df_significant <- results_df_significant %>%
  mutate(key = paste(grna_target, response_id, sep = "_"))


# Step 3: Find the unique keys in each set
scmageck_keys <- unique(scmageck_set$key)
results_df_keys <- unique(results_df_set$key)

# Step 4: Create the Venn diagram
venn_data <- list(Scmageck = scmageck_keys, Results_df = results_df_keys)

venn.plot <- venn.diagram(
  x = venn_data,
  category.names = c("Scmageck", "Sceptre"),
  filename = NULL,  # Not saving to file, but rendering in the plot window
  output = TRUE
)

# Display the Venn diagram using grid.draw
grid.newpage()
grid.draw(venn.plot)



### find the overlap and create correlation plot

overlap_keys <- intersect(scmageck_set$key, results_df_set$key)

# Step 4: Merge the datasets based on overlapping keys
scmageck_overlap <- scmageck_significant %>%
  filter(key %in% overlap_keys)

results_df_overlap <- results_df_significant %>%
  filter(key %in% overlap_keys)

merged_df <- merge(scmageck_overlap, results_df_overlap, by = "key", suffixes = c("_scmageck", "_sceptre"))

# Step 5: Create correlation plots for pval and expression_change
# Pval correlation plot
pval_plot <- ggplot(merged_df, aes(x = pval_scaled_scmageck, y = pval_scaled_sceptre)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
  labs(title = "Correlation of P-values", x = "scmageck P-value", y = "sceptre P-value") +
  theme_minimal()


# Expression change correlation plot
expr_change_plot <- ggplot(merged_df, aes(x = expr_change, y = log_2_fold_change)) +
  geom_point() +
    geom_smooth(method = "lm", formula = y ~ x + 0, col = "blue") +  # Force the line through zero
  stat_cor(aes(label = paste(..r.label.., ..rr.label.., sep = "~`,`~")), method = "pearson", label.x = 0) +
  labs(title = "Correlation of Expression Change",
       x = "Scmageck Expression Change",
       y = "Sceptre Expression Change") +
  theme_minimal()

expr_change_plot <- ggplot(merged_df, aes(x = expr_change, y = log_2_fold_change)) +
  geom_point() +
  geom_smooth(method = "lm", col = "blue") +
   stat_cor(aes(label = paste(..r.label.., ..rr.label.., sep = "~`,`~")), method = "pearson", label.x = 0) +
  labs(title = "Correlation of Expression Change", x = "Scmageck Expression Change", y = "Sceptre Expression Change") +
  theme_minimal()

# Display the plots
print(pval_plot)
print(expr_change_plot)


pdf(paste0(outdir, "/sceptre_scmageck_correlation.pdf"), height = 6, width = 12)
grid.draw(venn.plot)
pval_plot
expr_change_plot
 dev.off()

```


```{r}
#let's look at some gene enrichments?

#load peak data with snps and traits
peaks <- read_tsv("/g/steinmetz/project/otar/select_enhancer_peaks/Final_peaks_large_screen_2024-03-01.tsv", show_col_types = FALSE)


allergic_disease <- peaks %>% filter(trait == "Allergic_disease")
Ankylosing_spondylitis <-peaks %>% filter(trait == "Ankylosing_spondylitis")
Asthma <- peaks %>% filter(trait == "Asthma")
Crohns_disease <-  peaks %>% filter(trait == "Crohns_disease")
Celiac_disease <-  peaks %>% filter(trait == "Celiac_disease")
Eczema <-  peaks %>% filter(trait == "Eczema")
Inflammatory_bowel_disease <-  peaks %>% filter(trait == "Inflammatory_bowel_disease")
Multiple_sclerosis <-  peaks %>% filter(trait == "Multiple_sclerosis")
Primary_biliary_cholangitis <-  peaks %>% filter(trait == "Primary_biliary_cholangitis")
Primary_biliary_cirrhosis <-peaks %>% filter(trait == "Primary_biliary_cirrhosis")
Primary_sclerosing_cholangitis <-peaks %>% filter(trait == "Primary_sclerosing_cholangitis")
Psoriasis <-peaks %>% filter(trait == "Psoriasis")
Rheumatoid_arthritis <-peaks %>% filter(trait == "Rheumatoid_arthritis")
Systemic_lupus_erythematosus <-peaks %>% filter(trait == "Systemic_lupus_erythematosus")
Type_1_diabetes <-peaks %>% filter(trait == "Type_1_diabetes")
Ulcerative_colitis <-peaks %>% filter(trait == "Ulcerative_colitis")

results_df_significant <- results_df%>% filter(significant==TRUE)
results_df_AD <- results_df %>%  filter(grna_target %in% allergic_disease$peak) %>% filter(significant==TRUE)
results_df_AS <- results_df %>%  filter(grna_target %in% Ankylosing_spondylitis$peak) %>% filter(significant==TRUE)
results_df_Ast <- results_df %>%  filter(grna_target %in% Asthma$peak) %>% filter(significant==TRUE)
results_df_CeD <- results_df %>%  filter(grna_target %in% Celiac_disease$peak) %>% filter(significant==TRUE)
results_df_CD <- results_df %>%  filter(grna_target %in% Crohns_disease$peak) %>% filter(significant==TRUE)
results_df_Ecz <- results_df %>%  filter(grna_target %in% Eczema$peak) %>% filter(significant==TRUE)
results_df_IBD <- results_df %>%  filter(grna_target %in% Inflammatory_bowel_disease$peak) %>% filter(significant==TRUE)
results_df_MS <- results_df %>%  filter(grna_target %in% Multiple_sclerosis$peak) %>% filter(significant==TRUE)
results_df_PBCh <- results_df %>%  filter(grna_target %in% Primary_biliary_cholangitis$peak) %>% filter(significant==TRUE)
results_df_PBC <- results_df %>%  filter(grna_target %in% Primary_biliary_cirrhosis$peak) %>% filter(significant==TRUE)
results_df_PSC <- results_df %>%  filter(grna_target %in% Primary_sclerosing_cholangitis$peak) %>% filter(significant==TRUE)
results_df_Psor <- results_df %>%  filter(grna_target %in% Psoriasis$peak) %>% filter(significant==TRUE)
results_df_RA <- results_df %>%  filter(grna_target %in% Rheumatoid_arthritis$peak) %>% filter(significant==TRUE)
results_df_SLE <- results_df %>%  filter(grna_target %in% Systemic_lupus_erythematosus$peak) %>% filter(significant==TRUE)
results_df_T1D <- results_df %>%  filter(grna_target %in% Type_1_diabetes$peak) %>% filter(significant==TRUE)
results_df_UC <- results_df %>%  filter(grna_target %in% Ulcerative_colitis$peak) %>% filter(significant==TRUE)

gene_list_all <- unique(results_df$response_id)
gene_list_sig <- unique(results_df_significant$response_id)
gene_list_AD <- unique(results_df_AD$response_id)
gene_list_AS <- unique(results_df_AS$response_id)
gene_list_Ast <- unique(results_df_Ast$response_id)
gene_list_CeD <- unique(results_df_CeD$response_id)
gene_list_CD <- unique(results_df_CD$response_id)
gene_list_Ecz <- unique(results_df_Ecz$response_id)
gene_list_IBD <- unique(results_df_IBD$response_id)
gene_list_MS <- unique(results_df_MS$response_id)
gene_list_PBCh <- unique(results_df_PBCh$response_id)
gene_list_PBC <- unique(results_df_PBC$response_id)
gene_list_PSC <- unique(results_df_PSC$response_id)
gene_list_Psor <- unique(results_df_Psor$response_id)
gene_list_RA <- unique(results_df_RA$response_id)
gene_list_SLE <- unique(results_df_SLE$response_id)
gene_list_T1D <- unique(results_df_T1D$response_id)
gene_list_UC <- unique(results_df_UC$response_id)



#here fill in the disease gene_list
gene_entrez <- bitr(gene_list_UC, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)
gene_all_entrez <- bitr(gene_list_all, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)

go_enrichment <- enrichGO(gene         = gene_entrez$ENTREZID,
                          OrgDb        = org.Hs.eg.db,
                          ont          = "BP",  # "BP" for Biological Process, "MF" for Molecular Function, "CC" for Cellular Component
                          pAdjustMethod = "BH",
                          universe = gene_all_entrez$ENREZID,
                          pvalueCutoff  = 0.05,
                          qvalueCutoff  = 0.05,
                          readable      = TRUE)

# View the results
head(go_enrichment)


kegg_enrichment <- enrichKEGG(gene         = gene_entrez$ENTREZID,
                              organism     = 'hsa',  # 'hsa' for human
                              pvalueCutoff = 0.05, 
                              universe = gene_all_entrez$ENREZID)

# View the results
head(kegg_enrichment)

# Dotplot for GO Enrichment
dotplot(go_enrichment, showCategory = 10, title = "GO Enrichment")

# Dotplot for KEGG Enrichment
dotplot(kegg_enrichment, showCategory = 10, title = "KEGG Pathway Enrichment")
  ```