
# sceptre results from E-G mapping by differential expression analysis
results:
  with_promoterC:
    file: "resources/results_df.csv"
    group_col: "panel"

# genome annotations  
genome: "resources/hg38.gtf"

# ENCODE portal accessions for chromatin assay files
chromatin_assays:
  DNase-seq: ENCFF600IHC
  H3K27ac: ENCFF151LJA
  H3K4me1: ENCFF075XMI
  H3K4me3: ENCFF546IYU
  H3K9me3: ENCFF169XPR
  H3K27me3: ENCFF921HWX

# need to download hic file from ENCODE portal: https://www.encodeproject.org/files/ENCFF355VJW/@@download/ENCFF355VJW.hic 
hic: 
  file: "/scratch/users/agschwin/otar/ENCFF355VJW.hic"
  resolution: 5000

# other CRE and gene-level features
eRNA_counts: "resources/results_df_annotated_241013.eRNA.annotated.csv"
gene_disease_info: "resources/annotated_genes_dataframe.tsv"

# E-G pair prioritization for CRE screen and TAP-seq target gene panels
eg_prioritization: "resources/prioritised_gene_list_100kb_up_downstream_eQTL_GRN_aim1_E2G_nonGWAS_extended_windows_2024-03-01.tsv"
tapseq_gene_panels: "resources/Library_panels_2024-03-02.qs"
