## Process guide assignment matrix generated by SCEPTRE and save for subsequent analyses

suppressPackageStartupMessages({
  library(Matrix)
  library(sceptre)
  library(ondisc)
})

# load guide output guide assignment matrix
guide_assignments <- readRDS("./sceptre_outputs/grna_assignment_matrix.rds")

# directory containing input sceptre object
data_dir <- "/g/steinmetz/project/otar_2063/promoter_screen/processing/combine_data/results/combined_sceptre_filtered"

# load sceptre object
sceptre_object <- read_ondisc_backed_sceptre_object( 
  sceptre_object_fp = file.path(data_dir, "sceptre_object.rds"),
  response_odm_file_fp = file.path(data_dir, "gene.odm"),
  grna_odm_file_fp = file.path(data_dir, "grna.odm")
)

# set guide assignment matrix column names to cell ids
colnames(guide_assignments) <- rownames(sceptre_object@covariate_data_frame)

# save processed guide assigments matrix to RDS file
saveRDS(guide_assignments, file = "./grna_assignment_matrix.rds")

# write processed guide assigments matrix to Matrix Market files 
dir.create("matrix", showWarnings = FALSE)
writeMM(guide_assignments, file = "./matrix/grna_assignment_matrix.mtx")
writeLines(rownames(guide_assignments), con = "./matrix/grna_assignment_matrix_rownames.txt")
writeLines(colnames(guide_assignments), con = "./matrix/grna_assignment_matrix_colnames.txt")
